name       : libpeas
version    : 1.26.0
release    : 19
source     :
    - https://download.gnome.org/sources/libpeas/1.26/libpeas-1.26.0.tar.xz : a976d77e20496479a8e955e6a38fb0e5c5de89cf64d9f44e75c2213ee14f7376
license    : LGPL-2.0-only
component  : desktop.gnome.core
summary    : libpeas provides a plugin framework for GLib applications
description: |
    libpeas provides a plugin framework for GLib applications
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
setup      : |
    %meson_configure -Dpython2=true
build      : |
    %ninja_build
install    : |
    %ninja_install
