name        : libpeas
version     : 1.16.0
release     : 8
source     :
    - http://ftp.gnome.org/pub/gnome/sources/libpeas/1.16/libpeas-1.16.0.tar.xz : b093008ecd65f7d55c80517589509698ff15ad41f664b11a3eb88ff461b1454e
license     :
    - LGPL-2.0
summary     : libpeas provides a plugin framework for GLib applications
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.5)
description : |
    libpeas provides a plugin framework for GLib applications
setup      : |
    %configure --disable-static \
               --enable-python2 \
               --enable-python3 \
               --enable-gtk \
               --disable-compile-warnings
build      : |
    %make
install    : |
    %make_install
