name       : libpeas
version    : 1.24.0
release    : 18
source     :
    - https://download.gnome.org/sources/libpeas/1.24/libpeas-1.24.0.tar.xz : 0b9a00138c129a663de3eef5569b00ace03ce31d345f7af783768e9f35c8e6f9
license    : LGPL-2.0-only
component  : desktop.gnome.core
summary    : libpeas provides a plugin framework for GLib applications
description: |
    libpeas provides a plugin framework for GLib applications
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
setup      : |
    %meson_configure -Dpython2=true
build      : |
    %ninja_build
install    : |
    %ninja_install
