name       : libpeas
version    : 1.34.0
release    : 26
source     :
    - https://download.gnome.org/sources/libpeas/1.34/libpeas-1.34.0.tar.xz : 4305f715dab4b5ad3e8007daec316625e7065a94e63e25ef55eb1efb964a7bf0
homepage   : https://wiki.gnome.org/Projects/Libpeas
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : libpeas provides a plugin framework for GLib applications
description: |
    libpeas is a gobject-based plugins engine, and is targetted at giving every application the chance to assume its own extensibility.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
rundeps    :
    - python-gobject
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
