name       : libpeas
version    : 1.18.0
release    : 10
source     :
    - http://ftp.gnome.org/pub/gnome/sources/libpeas/1.18/libpeas-1.18.0.tar.xz : bf49842c64c36925bbc41d954de490b6ff7faa29b45f6fd9e91ddcc779165e26
license    :
    - LGPL-2.0
summary    : libpeas provides a plugin framework for GLib applications
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.5)
description: |
    libpeas provides a plugin framework for GLib applications
setup      : |
    %configure --disable-static \
               --enable-python2 \
               --enable-python3 \
               --enable-gtk \
               --disable-compile-warnings
build      : |
    %make
install    : |
    %make_install
