name       : libpeas
version    : 1.22.0
release    : 15
source     :
    - https://download.gnome.org/sources/libpeas/1.22/libpeas-1.22.0.tar.xz : 5b2fc0f53962b25bca131a5ec0139e6fef8e254481b6e777975f7a1d2702a962
license    : LGPL-2.0-only
component  : desktop.gnome.core
summary    : libpeas provides a plugin framework for GLib applications
description: |
    libpeas provides a plugin framework for GLib applications
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
setup      : |
    %configure --disable-static \
               --enable-python2 \
               --enable-python3 \
               --enable-gtk \
               --disable-compile-warnings
build      : |
    %make
install    : |
    %make_install
