name       : libpeas
version    : 1.20.0
release    : 12
source     :
    - http://ftp.gnome.org/pub/gnome/sources/libpeas/1.20/libpeas-1.20.0.tar.xz : f392fffe2dc00072a51bb2a1b274224a06bdc5f9c3b3c0ac4816909e9933d354
license    : LGPL-2.0
component  : desktop.gnome.core
summary    : libpeas provides a plugin framework for GLib applications
description: |
    libpeas provides a plugin framework for GLib applications
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.5)
setup      : |
    %configure --disable-static \
               --enable-python2 \
               --enable-python3 \
               --enable-gtk \
               --disable-compile-warnings
build      : |
    %make
install    : |
    %make_install
