name       : libpeas
version    : 1.30.0
release    : 23
source     :
    - https://download.gnome.org/sources/libpeas/1.30/libpeas-1.30.0.tar.xz : 0bf5562e9bfc0382a9dcb81f64340787542568762a3a367d9d90f6185898b9a3
homepage   : https://wiki.gnome.org/Projects/Libpeas
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : libpeas provides a plugin framework for GLib applications
description: |
    libpeas is a gobject-based plugins engine, and is targetted at giving every application the chance to assume its own extensibility.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
rundeps    :
    - python-gobject
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
